language: "lt"
questionnaire_language: "lt"
title: IŠGELBĖK INTERNETĄ EUROPOJE
action: Prisijunk ir veik dabar! Nusiųsk žinutę savo nacionalinei reguliavimo institucijai
keywords:
  - Tinklo neutralumas
  - Atviras internetas
  - Specializuotos paslaugos
  - Duomenų srauto valdymas
  - Mokamos lenkimo juostos
  - Nulinis reitingas
  - Europa
  - Bendroji telekomunikacijų bendrovių rinka
  - Tinklo neutralumas
