language: "nl"
questionnaire_language: "nl"
title: RED HET INTERNET IN EUROPA
action: Doe met ons mee een neem actie! Stuur een bericht naar uw regelgevende instantie.
keywords:
  - netneutraliteit
  - open internet
  - gespecialiseerde diensten
  - verkeersbeheer
  - betaalde snelle verbindingen
  - zero rating
  - Europa
  - eengemaakte telecommarkt
  - netwerkneutraliteit
