language: "it"
questionnaire_language: "it"
title: SAVE THE INTERNET IN EUROPA
action: Unisciti a noi e agisci! Invia un messaggio al tuo ente normatore
keywords:
 - neutralità della rete
 - internet aperto
 - servizi specializzati
 - gestione del traffico
 - corsie preferenziali a pagamento
 - zero-rating/accesso gratuito
 - Europa
 - mercato unico Telecom
 - neutralità di internet
 - Italy
 - Italia
 - Autorità per le Garanzie nelle Comunicazioni (AGCOM)
 - AGCOM
