language: "cz"
questionnaire_language: "cz"
title: ZACHRAŇTE INTERNET V EVROPĚ
action: Přidejte se k nám a jednejte! Napište vašemu regulačnímu úřadu
keywords:
  - síťová neutralita
  - otevřený internet
  - specializované služby
  - řízení provozu
  - placené „rychlé pruhy“
  - zero rating
  - Evropa
  - Jednotný telekomunikační trh
  - síťová neutralita
  - net neutrality
  - network neutrality
  - Günther Oettinger
  - Internet
  - Open internet
  - Specialized services
  - Traffic management
  - BEREC
  - paid fast lanes
  - zero-rating
  - Europe
  - EU
  - Telecom Single Market
  - Czech Telecommunication Office, CTU
  - CZECH REPUBLIC 
